In [2]:
import numpy as np
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
M.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [4]:
M.trace()

15

In [5]:
M[0]

array([1, 2, 3])

In [8]:
for row in M:
    print(row[0])

1
4
7


In [14]:
M[1][1]

5

M[a][b] es igual que M[a,b]

M[][1] No se puede, siempre debe ir especificado el renglón

In [19]:
M[1,]

array([4, 5, 6])

In [22]:
M[1]

array([4, 5, 6])

In [12]:
M[1][2]

6